### PR TITLE
Added support for apache type paths e.g mysql-connector-java-5.1.22.jar 

### PR DESCRIPTION
**Pull request by javadba**
Hi Nikita,  i like your convenience script for local maven installs. However I do not use eclipse, it is useful for random jars.   The patch includes 3 new cmd line parameters, and have updated the README.md . 

take a look see if you want to include it, either way pls let me know what you decide/think.

stephen boesch

### CODE REVIEW

**Comment by nikita-volkov** [comment]
Hello, Stephen. 
1. Why a diff-file and not just changes to the script itself? You kinda elude the whole point of using git and github with that.
2. This script was supposed to be a simple tool and I don't want to overly complicate things by introducing quite a few arguable flags. So, sorry, I won't merge unless this gets a notable amount of votes.
3. You know, nobody stops you from evolving this project any way you want on your own fork. This especially concerns the projects which require no publication to any package repositories, such as in our case.

**Comment by javadba** [comment]
I did update the script, did you not see that?  I'll double check the pull request.

It is up to you though, i added helpful stuff, but it's your project.

**Comment by javadba** [comment]
So yes, I see that i missed the actual .py file (the whole point of it) in the pull request. I will add it in.  Then you decide.

**Comment by javadba** [comment]
It's in your court now. 

thanks
stephenb

**Comment by nikita-volkov** [comment]
As I said earlier:

> This script was supposed to be a simple tool and I don't want to overly complicate things by introducing quite a few arguable flags. So, sorry, I won't merge unless this gets a notable amount of votes.

Also, to tell you the truth, you've just made yourself a reputation of being neglectful with the diff-or-not, a bunch of redundantly commented lines of code and how you updated the "readme". This means that I have to spend time to carefully study and test your code before I merge which I just don't have right now.

On the bright side, now you have your own fork of the project which you can evolve however you want. So good luck!

**Pull request closed without merging**
